### ISSUE TITLE
why has many unexcepted error that breaking the app when Vue.config.debug=true(chrome)

### ISSUE THREAD

**Issue by ccqgithub** [kazupon/vue-validator#111]
just like https://jsfiddle.net/ujd0jL2s/

it is just one of the large numbers error like that ……

it is ok in firefox, and if i turn the debug mode off, it is ok (but also many warnings)。

if it is just a warning, why the app is not working?

**Comment by kazupon** [comment]
Related #35 #103

**Comment by kazupon** [comment]
Sorry, I cannot find a solution to this issue yet.
This issue is difficult.

I'm asking the advise about related issue at below forum.

http://forum.vuejs.org/topic/957/how-to-avoid-evaluating-expression-warning-for-plugin-author

This issue is occuring when we using development version of vue.js

In development of app, we can avoid this issue by setting the `Vue.config.warnExpressionErrors = false`.

I'll try to write the `README.md` later. :smile_cat:

**Comment by ccqgithub** [comment]
ooo,  very tks  for your work, let our work more comfortable……^_^
but i think this is not a good solution，because if i do that, i will lose sight of many other  'mistakes'。if it is just a warning, there's no problem, but it let app not working ……
i think, (just like u have done)the question should be thrown open to public discussion, maybe someone know how to fix it……

**Comment by kazupon** [comment]
Yes, me too.
I agree with you.

This solution is not good solution.
I will ask @yyx990803 to an opinion later. :smile_cat:

**Comment by kazupon** [comment]
fixed
https://github.com/vuejs/vue-validator/releases/tag/v2.0.0-alpha.12
