### ISSUE TITLE
field located in child component from validator does not work

### ISSUE THREAD

**Issue by revati** [kazupon/vue-validator#131]
If i have component with 

``` vue
<validator name="myValidator">
  <child-component></child-component>
</validator>
```

And `child-component` with

``` vue
<input v-validate:username="['required']" />
```

vue validator is complaining `Uncaught TypeError: Cannot read property 'validate' of undefined`. It relays on `this.vm.$options._validator` but in child component it is undefined (because `this` is not the same)

Are there any reasonable ways how to pass validator to child component? 
Why `<validator name="myValidator">` is required at all?
Are there any drawbacks if each field is wrapped within new instance of `<validator name="myValidator">`?

**Comment by kazupon** [comment]
Thank you for your feedback.

> Are there any reasonable ways how to pass validator to child component? 

I recommend that you should wrap the `validator` element directive (`<validator>`) to your component (`<child-component>`) that has validatable element (e.g, `input`, `checkbox`), because `validator` element directive will check validatable elements of internal, and dynamically set the validation result to validator scope (prefixed with `$`).

**Comment by kazupon** [comment]
Close (in-activity)
