### ISSUE TITLE
Get $validator inside component from parent component

### ISSUE THREAD

**Issue by ikristher** [kazupon/vue-validator#154]
How can I get the $validator inside a sub component from my root component or root vm.

Thanks

**Comment by kazupon** [comment]
I recommend that you should use the state management architecture as flux / reduex, because if you use validation result from outside component or outside vm, your application become complex.

the following the vuex example code:

``` html
<input v-validate:msg @valid="updateValidMessage">
```

``` javascript
// ...
methods: {
  updateValidMessage: function () {
    store.actions.updateValidMessage('msg', true)
  }
}
```

References:
- [State Management](http://vuejs.org/guide/application.html#State_Management)
- [Form Handling](http://vuex.vuejs.org/en/forms.html)
- [Event](https://github.com/vuejs/vue-validator#event)

**Comment by kazupon** [comment]
Close (inactivity)
