### ISSUE TITLE
Cannot read property 'childNodes' of undefined when updating

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [kazupon/vue-validator#177]
Hello,

We updated vue validator in our project from version `2.0.0.alpha-21` to `2.0.0.beta-3` and we are getting this error: `Cannot read property 'childNodes' of undefined`. 

We know there is a problem with `vue-1.0.19` right now but this is not a duplicate since we fixed vue to `1.0.16`.

Is there any migration guide we need to follow or is it an unknown bug ? 

Thank you

**Comment by vnctaing** [comment]
I have the same problem whenever I try to use more than one `<validator>`

I am using `vue-validator@2.0.0-beta.3` and `vue@1.0.18`

**Comment by kazupon** [comment]
Hi !!
Thank you for your reporting!!

Can you provide the repro code with jsfiddle or webpackbin or etc please ?

**Comment by kazupon** [comment]
Close (in-activity)

**Comment by GuillaumeLeclerc** [comment]
Sorry for the inactivity but I'm not able to reproduce in a fiddle since I don't know how to use `vue-validator`, one of my cowerkers did this. I just ran npm update and everything stopped working. I don't have more insights.

**Comment by kazupon** [comment]
You can fork the jsfiddle template, and add the vue-validator.js at external resouces.
http://jsfiddle.net/5sH6A/

**Comment by kating** [comment]
I have same problem, and made a repro code. 
http://jsfiddle.net/fvkux5dq/

using vue-validator@2.0.0 and vue@1.0.20

I noticed:
- This happen when using custom component and more than one validator element.
- vue-validator pass not HTMLElement but DocumentFragment to FragmentFactory constructor
- FragmentFactory set linker from cache, using key generated from HTMLElement. DocumentFragment instead of HTMLElement can't create proper cache key. (@vuejs)
