### ISSUE TITLE
Uncaught TypeError: Cannot read property 'invalid' of undefined

### ISSUE THREAD

**Issue by shinygang** [kazupon/vue-validator#340]
### vue & vue-validator version
2.0.3, 3.0.0-alpha.1

### Reproduction Link

https://jsfiddle.net/7kzcgy3p/

### What is Expected?
![error](http://ww4.sinaimg.cn/large/79462090gw1f9sm6ezawmj21hb0p5tn8.jpg)
### What is actually happening?
`Uncaught TypeError: Cannot read property 'invalid' of undefined`

**Comment by shinygang** [comment]
the other question:
1、hao to activate the validation1 validate in my js code. which method?
2、when will the V3‘s document be released?

**Comment by farrance** [comment]
I'm having the same issue.

**Comment by kazupon** [comment]
Thank you for your feedback.
I seem that is bug ...
I'll try to fix next release.

Sorry, I'm busy hard to work ...
Please wait :bow:

**Comment by mesis** [comment]
I'm having the same issue here.

**Comment by maxKimoby** [comment]
The bug makes the plugin unusable when there are more than a single validity tag, so generally unusable. It seems that only the first validity element is processed. I know that because I put a watch on $validation.myValidator and when it changes from undefined to something, it only contains the first validity element.

Really needs documentation and a quick and functional release for 2.0, this is really annoying for people upgrading from 1.x that were using the previous VueValidator release (which was marvelous).

Edit : The plugin seems to be functional even though the error still persists. But something throwing an error is never functional for a good programmer.

**Comment by hxd520love** [comment]
![image](https://cloud.githubusercontent.com/assets/7676262/20638567/cbac4c6e-b3e5-11e6-9838-4cf9d3123394.png)
![image](https://cloud.githubusercontent.com/assets/7676262/20638572/00f6081a-b3e6-11e6-9818-ad8bcccf6899.png)
一开始会有三个undefined，然后才是对的。而且按照文档写的，请大大查看
