### ISSUE TITLE
"Error when evaluating expression validation.name.invalid"

### ISSUE THREAD

**Issue by dwightjack** [kazupon/vue-validator#35]
Hi, 

great work on this plugin!

When I access to the validation object, i got in the console the following message:

```
[Vue warn]: Error when evaluating expression "validation.name.invalid"
```

While this doesn't break the application I wonder if I'm missing something in the setup.

Thanks in advance!

**Comment by kazupon** [comment]
I think that there are not problem in your setup code.
This is small problem of vue-validator.

See http://vuejs.org/guide/best-practices.html#Data_Initialization

But it does not effect in application behavior.
That's OK. :smile: 

In the v2.0, I'm going to resolve it !

**Comment by dwightjack** [comment]
Ok thanks for the explanation!

**Comment by PeakTai** [comment]
I met the same problem.If the level is too much,it's not convenient to initialize data like this instead of an empty object.I do this now:

```
validation&&validation.form.name.invalid
```

**Comment by oliverzy** [comment]
I found if I turned on Vue.config.debug, Vue will throw exception, the app will stop working.

**Comment by EHackettTriCore** [comment]
+1

**Comment by seanwash** [comment]
I can also verify this. My application was breaking until I set `Vue.config.debug` to `false`. I get the same warning, although that app now behaves as expected.

**Comment by kazupon** [comment]
Sorry, I cannot find a solution to this issue yet.
This issue is difficult.

I'm asking the advise about related issue at below forum.

http://forum.vuejs.org/topic/957/how-to-avoid-evaluating-expression-warning-for-plugin-author

This issue is occuring when we using development version of vue.js

In development of app, we can avoid this issue by setting the `Vue.config.warnExpressionErrors = false`.

I'll try to write the `README.md` later. :smile_cat:
