### ISSUE TITLE
Dynamic setting field, how to set up validator

### ISSUE THREAD

**Issue by lynzz** [kazupon/vue-validator#46]
code：

http://jsfiddle.net/lynzz/8zx3cnh6/

Business scene , think through the following settings, create a form with validation:

```
var fileds = [{
    label: '标题',
    name: 'title',
    value: '我就是我',
    validate:'required',
    placeholder: '请填写标题'
}, {
    label: '描述',
    name: 'description',
    value: '我就是我，是颜色不一样的烟火',
    validate:'required',
    placeholder: '请填写描述'
}];
```

Encountered do not know how to set v-model and validate issues.

PS:  forgive my poor English

**Comment by kazupon** [comment]
Hi @lynzz !!

Thank you for your reporting.

If anything, this issue is a topic of vuejs/discussion.

Maybe, you will probably helpful the following `v-model` setup issues.
- Dynamic v-model directive
  https://github.com/yyx990803/vue/issues/1056
- Dynamically associate form elements to models
  https://github.com/vuejs/Discussion/issues/19

But `v-validator` cannot support dynamic validator setup.

In Currently, you need to implement validation with the `$compile` or element directive.

I think that will support the v2.0 later.

**Comment by lynzz** [comment]
Thanks! :smile:

**Comment by amanpatel** [comment]
@kazupon So are dynamic directives supported in Vue 1.x ?

I'd love to use vue-validator, but if I can't apply or register directives programmatically within a component, it wouldn't fit my needs.

**Comment by revati** [comment]
Are there any updates on this?

```
v-validate:{{ id }}="{{ rules }}"

// throws error
Uncaught InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': '}}' is not a valid attribute name.
```

**Comment by kazupon** [comment]
Sorry, In current version (2.0-alpha.9), We don't support the dynamic validator (dynamic component).

I'll plan to support.
please wait. :smile_cat:

**Comment by lazabogdan** [comment]
@lynzz @kazupon How about this? http://jsfiddle.net/6f9g2a5p/4/

Probably not the ideal way, but I can't think of another workaround.

Let me know what you think.

**Comment by kazupon** [comment]
Please see #131

**Comment by lazabogdan** [comment]
@kazupon thanks! Looking good. I can finally get rid of those many validator instances and use fields.
