### ISSUE TITLE
Compatibility w/ Vue 1.0 Beta

### ISSUE THREAD

**Issue by davidkhess** [kazupon/vue-validator#67]
With a number of breaking changes (of which at least removal of "inherit" will impact Vue-Validator), what is the schedule/plan to port Vue-Validator to Vue 1.0 Beta?

**Comment by kazupon** [comment]
Until recently, I had been develop from full-scratch as v2.0 for Vue beta.
But I'm translating Vue 1.0 documents as high priority task for japanese users now because Vue 1.0 release be expected the end of October or later.

See the tweet of vue.js twitter account:
https://twitter.com/vuejs/status/652593449636634625

When I finished document translation, I resume the development vue-validator.
Sorry, please wait :wink:

**Comment by davidkhess** [comment]
I understand. Thanks for your hard work on that and vue-validator!

**Comment by kazupon** [comment]
thanks!

**Comment by shredmaster** [comment]
I understand 2.0 is still under development. Is there a dev branch compatible with vue 1.0 right now?

**Comment by kazupon** [comment]
@shredmaster 
sorry, `dev` branch not compatible.

**Comment by nigelmst** [comment]
@kazupon do you have an eta on when we can have access to the 2.0 `dev`?

**Comment by kazupon** [comment]
I published 2.0.0-alpha.1
https://github.com/vuejs/vue-validator/releases
