### ISSUE TITLE
V-IF and validation

### ISSUE THREAD

**Issue by karol-f** [kazupon/vue-validator#69]
Hi, I would like to ask for best approach to dynamic field validation. As you can see in https://jsfiddle.net/p6r5muv4/ fiddle:
- adding v-model fields works ok
- removing v-model field using v-if, clears **validation** variable for other fields too

I have few questions:
- is there good approach to deal with it (no matter how many **v-validate** expressions you have)?
- do next version of **vue-validate** handle such situations?

It would be nice to have same behaviour as in Angular validation, when if you remove **model** from DOM, validation woun't touch such fragment and just update for the rest.

Regards!

![Validation](http://fabjanczuk.pl/programming/validation.gif)

**Comment by kazupon** [comment]
Hi !!
Thank you for your report.

I recognize this issue as bug (similar #52).
This bug has occurring because of the bad design of vue-validator implementation.
This bug occurs when we use the `v-if` direcitve.
For this reason, To avoid this problem, you need to use the `v-show` directive.

In v2.0, I also reference the design of angluar. it may be similar. :wink:

**Comment by karol-f** [comment]
@kazupon Thank you for explanation. Regards!

**Comment by kazupon** [comment]
Fixed in 2.0.0-alpha.1

**Comment by karol-f** [comment]
@kazupon nice!

**Comment by scoutkirkolson** [comment]
I'm using 2.0.0.-alpha.22 but still experiencing this issue

**Comment by andrewdang17** [comment]
I'm still having this issue too.
